services:
  db:
    image: saplabs/hanaexpress:latest
    restart: on-failure
    hostname: 3c423914c15f
    ports:
      - 39013:39013
      - 39017:39017
      - 39041-39045:39041-39045
      - 1128-1129:1128-1129
      - 59013-59014:59013-59014
    command: "--master-password Password1! --agree-to-sap-license"
    volumes:
      - ./hana/data/:/hana/mounts
