name: CI

on:
  push:
    paths-ignore:
      - "*.md"
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    # services:
    #   hana:
    #     image: saplabs/hanaexpress:latest
    #     options: >-
    #       --master-password Password1!
    #       --agree-to-sap-license
    #       --hostname 3c423914c15f

    strategy:
      matrix:
        node-version: [16, 18, 20, 22]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Start SAP HANA Express container
        run: |
          docker run -d --name hana \
            -p 39013:39013 \
            -p 39017:39017 \
            -p 39041-39045:39041-39045 \
            -p 1128-1129:1128-1129 \
            -p 59013-59014:59013-59014 \
            saplabs/hanaexpress:latest \
            --master-password Password1! \
            --agree-to-sap-license \
            --hostname 3c423914c15f
      - name: Wait for SAP HANA startup to complete
        run: |
          echo "Waiting for SAP HANA Express to be ready (looking for 'Startup finished!')..."
          while ! docker logs hana 2>&1 | grep -q "Startup finished!"; do
            echo "Still waiting for SAP HANA to finish starting up..."
            echo "Current logs from SAP HANA container:"
            docker logs --tail 10 hana 2>&1 | tee -a $LOG_FILE
            sleep 5
          done
          echo "SAP HANA Express startup completed!"
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run db migrations
        run: npm run migrate
      - name: Run tests
        run: npm run ci
